KAGIRO_API_KEY = "mk-0d2e820dd3a9476c9f5546ae3fc58ee3"
KAGIRO_BASE_URL = "https://api.kagiro.net/v1"

BANDEL_API_KEY = "sk-qwen-8626801cf90d7ce3a914fa1c097070fe4b54600bf3c831e7"
BANDEL_BASE_URL = "https://bandelbanget.xyz/v1"
